name: Docker Images Build & Push to ghrc.io

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Test the python execution for consistency prior to docker build
        run: |
          echo "Setting up Python env and running tests."
          echo "py=$(which python) pip=$(which pip) flake8=$(which flake8) pytest=$(which pytest)"
          make init 
          . .venv/bin/activate 
          echo "py=$(which python) pip=$(which pip) flake8=$(which flake8) pytest=$(which pytest)"
          make check test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Use tag name
        run: echo "Tag is ${{ steps.get_tag.outputs.TAG_NAME }}"

      - name: Disclose the event_name
        run: echo "${{ github.event_name }}"

      - name: Build the Docker image and Push it to the registry-namespace indicated in REG_NS
        env:
          REG_NS: ghcr.io/emo-bon/emobon
          TAG_NAME: ${{ steps.get_tag.outputs.TAG_NAME }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          touch .env
          echo "Using registry namespace: $REG_NS"
          echo "Tag name: $TAG_NAME"
          # Use semver regex to decide if this is a release tag or fallback to 'latest'
          regex="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"
          if [[ $TAG_NAME =~ $regex ]]; then
            BUILD_TAG=$TAG_NAME
          else
            BUILD_TAG="latest"
          fi
          echo "Computed build tag: $BUILD_TAG"
          
          if [[ "$EVENT_NAME" == "pull_request" ]]; then
            echo "Pull request event: building and testing only."
            make docker-build docker-test
          else
            echo "Main/tags push: building, testing, and pushing."
            make docker-push
          fi
